---
# This is a sample database file for the ActiveRecord ORM
:development: &defaults
  :adapter: sqlite3
  :database: db/development.sqlite3

:test:
  <<: *defaults
  :database: db/test.sqlite3

:production:
  <<: *defaults
  :database: db/production.sqlite3
  
:rake:
  <<: *defaults